spring:
  datasource:
    platform: h2
    driverClassName: org.h2.Driver
    # url: jdbc:h2:mem:symbiosis;MODE=MySQL
    url: jdbc:h2:file:~/Computing/data/demo
    username: sa
    password: password
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
